apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ofn9m0moy-python
  janus-idp.io/tekton: ofn9m0moy-python
  backstage.io/kubernetes-id: ofn9m0moy-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ofn9m0moy-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
