apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ofn9m0moy-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ofn9m0moy-python 
  name: ofn9m0moy-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ofn9m0moy-python 
